### ISSUE TITLE
Search by card name

### ISSUE THREAD

**Issue by hrangel** [lukehorvat/graphql-trello#1]
Hey luke,

Is there anyway to search for cards (by name for instance)?

Can you provide examples?

Regards!

**Comment by lukehorvat** [comment]
Not yet. Trello's API doesn't offer this functionality, so it would have to be implemented in this package.

Easiest way to do it would be to fetch a board/list/member first (including its cards in the GraphQL query), and then perform a client-side search on all cards linked to that object. I do something similar to this in my [get-trello-board](https://github.com/lukehorvat/get-trello-board/blob/7ef20d3f7d/lib/index.js#L13) package, where I enable boards to be searched for by URL (functionality that Trello's API doesn't provide). It's not an ideal solution, but we don't have any other options.

I wasn't planning to add search-by-card-name to this package any time soon. But if it's something you really want, feel free to send me a pull request.
